fixed issue ``` == Compilation error in file lib/exq_ui_web/views/layout_view.ex == ** (RuntimeError) use Phoenix.HTML is no longer supported in v4.0.
To keep compatibility with previous versions, add {:phoenix_html_helpers, "~> 1.0"} to your mix.exs deps
and then, instead of "use Phoenix.HTML", you might:

    import Phoenix.HTML
    import Phoenix.HTML.Form
    use PhoenixHTMLHelpers

    (phoenix_html 4.1.1) expanding macro: Phoenix.HTML.__using__/1
    lib/exq_ui_web/views/layout_view.ex:3: ExqUIWeb.LayoutView (module)
    (elixir 1.15.7) expanding macro: Kernel.use/1
    lib/exq_ui_web/views/layout_view.ex:3: ExqUIWeb.LayoutView (module)
    expanding macro: ExqUIWeb.__using__/1
    lib/exq_ui_web/views/layout_view.ex:3: ExqUIWeb.LayoutView (module)
    (elixir 1.15.7) expanding macro: Kernel.use/2
    lib/exq_ui_web/views/layout_view.ex:3: ExqUIWeb.LayoutView (module)
    ```